name: La Brique Blue Pre-production CI/CD pipeline
on: 
  push:
    branches: [preprod]
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: 16.17.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn nx run-many --target=build --all    --prod  ;
      
  deploy:
    runs-on: ubuntu-latest 
    needs: [integrate]
    steps:
    - name: Deploy to Pre-production  Server
      uses: appleboy/ssh-action@master
      env:
        USER_PASSWORD: ${{ secrets.PRE_PRODUCTION_SERVER_PASSWORD }}
      with: 
        host: ${{ secrets.PRE_PRODUCTION_SERVER_HOST }}
        username: ${{ secrets.PRE_PRODUCTION_SERVER_USERNAME }}
        key: ${{ secrets.PRE_PRODUCTION_SSH_PRIVATE_KEY }}
        port: 22
        script_stop: true
        envs: USER_PASSWORD
        script: |
            cd lbb
            git stash
            git checkout preprod
            git pull origin preprod
            echo $USER_PASSWORD |sudo -S sh setup.sh
