name: La Brique Blue Pre-production Continuous Delivery pipeline
on: 
  push:
    branches: [preprod]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Deploy to Pre-production  Server
      uses: appleboy/ssh-action@master
      env:
        USER_PASSWORD: ${{ secrets.PRE_PRODUCTION_SERVER_PASSWORD }}
      with: 
        host: ${{ secrets.PRE_PRODUCTION_SERVER_HOST }}
        username: ${{ secrets.PRE_PRODUCTION_SERVER_USERNAME }}
        key: ${{ secrets.PRE_PRODUCTION_SSH_PRIVATE_KEY }}
        password: ${{ secrets.PRE_PRODUCTION_SERVER_PASSWORD }}
        port: 22
        script_stop: true
        envs: USER_PASSWORD
        script: |
            cd lbb
            git stash
            git checkout preprod
            git pull origin preprod
            echo $USER_PASSWORD |sudo -S sh setup.sh
