name: La Brique Blue production CI/CD pipeline
on:
  push:
    branches: [prod]
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lbb
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn nx run-many --target=build --all    --prod  ;

  deploy:
    runs-on: ubuntu-latest
    needs: [integrate]
    steps:
      - name: Deploy to Production  Server
        uses: appleboy/ssh-action@master
        env:
          USER_PASSWORD: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          envs: USER_PASSWORD
          script: |
            cd lbb
            git stash
            git fetch --tags
            git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
            echo $USER_PASSWORD |sudo -S sh setup.sh
